const STORAGE_KEY = "circe_validator_api_key";

export function getStoredApiKey(): string | null {
  if (typeof window === "undefined") return null;
  return window.localStorage.getItem(STORAGE_KEY);
}

export function setStoredApiKey(key: string): void {
  if (typeof window === "undefined") return;
  window.localStorage.setItem(STORAGE_KEY, key);
}

let inflight: Promise<string> | null = null;

/** Every browser gets its own API key on first visit, generated by the backend
 * and cached in localStorage — this is what scopes "New Validation" / "History"
 * to the person who submitted the run instead of showing everyone's runs. Users
 * who want the same history on another device can paste their key in via the
 * nav bar control instead of getting a fresh one. */
export async function ensureApiKey(apiBase: string): Promise<string> {
  const existing = getStoredApiKey();
  if (existing) return existing;
  if (!inflight) {
    inflight = fetch(`${apiBase}/api/keys`, { method: "POST" })
      .then((res) => {
        if (!res.ok) throw new Error("Failed to obtain an API key");
        return res.json();
      })
      .then((data: { api_key: string }) => {
        setStoredApiKey(data.api_key);
        return data.api_key;
      })
      .finally(() => {
        inflight = null;
      });
  }
  return inflight;
}
